### PR TITLE
Updated pypi license declaraton to use SPDX identifier in the license…

### PR DESCRIPTION
**Pull request by ethanwillis**
… field

### CODE REVIEW

**Comment by ethanwillis** [comment]
Fixes #62

**Comment by rsyring** [comment]
@ethanwillis per the email in #62, it looks like we should also use the classifier.  Could you add that too?

**Comment by ethanwillis** [comment]
@rsyring that's in line 53 of setup.py already.

**Comment by rsyring** [comment]
> @rsyring that's in line 53 of setup.py already.

One of the disadvantages of only looking at the PR diff is not having all the context.  :)

**Pull request merged**
